#!/bin/bash

LOC="`pwd`"

export PATH="$PATH:$LOC/maker/src/bin"
export PATH="$PATH:$LOC/external/bin"
export PATH="$PATH:$LOC/external/exe/blast/bin"
export PATH="$PATH:$LOC/external/exe/snap/bin"
export PATH="$PATH:$LOC/external/exe/repeatmasker"
export PATH="$PATH:$LOC/external/exe/exonerate/bin"
export PATH="$PATH:$LOC/external/exe/augustus/bin"

export PERL5LIB="$LOC/maker/lib"
export PERL5LIB="$PERL5LIB:$LOC/maker/perl/lib"
export PERL5LIB="$PERL5LIB:$LOC/external/lib/perl5"
export PERL5LIB="$PERL5LIB:$LOC/external/lib/perl5/x86_64-linux-thread-multi"

export PATH="$PATH:$LOC/cctools/bin"
export PERL5LIB="$PERL5LIB:$LOC/cctools/lib/perl5/site_perl/5.8.8/"

work_queue_worker $*

